package task

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"slop-generator/internal/config"
	"slop-generator/internal/inference"
	"slop-generator/internal/pipeline"
)

type memoryStore struct {
	tasks []Task
	err   error
}

func (s *memoryStore) Load() ([]Task, error) { return slices.Clone(s.tasks), s.err }
func (s *memoryStore) Save(tasks []Task) error {
	if s.err != nil {
		return s.err
	}
	s.tasks = slices.Clone(tasks)
	return nil
}

type stubProvider struct{ closed bool }

func (*stubProvider) Generate(context.Context, inference.Request) (inference.Result, error) {
	return inference.Result{Content: "generated by stub", Usage: &inference.Usage{Total: 7}}, nil
}
func (p *stubProvider) Close() { p.closed = true }

type stubRepository struct {
	commits, pushes, pulls int
	reject                 bool
	pullErr                error
}

func (*stubRepository) Identity(context.Context, config.Repository) (string, error) {
	return "stub-repository", nil
}
func (*stubRepository) Prepare(_ context.Context, _ config.Repository, work string) (string, error) {
	return "base", os.MkdirAll(work, 0700)
}
func (r *stubRepository) Commit(_ context.Context, work string, paths []string, message, hooks string) (string, error) {
	r.commits++
	if _, err := os.Stat(filepath.Join(work, paths[0])); err != nil {
		return "", err
	}
	return "saved-sha", nil
}
func (r *stubRepository) Publish(context.Context, string, string, string) error {
	r.pushes++
	if r.reject {
		return errors.New("temporary publication failure")
	}
	return nil
}

func (r *stubRepository) Pull(context.Context, config.Repository) error { r.pulls++; return r.pullErr }

func TestInjectedPipelineAndAdapters(t *testing.T) {
	provider := &stubProvider{}
	runs := 0
	repo := &stubRepository{reject: true}
	store := &memoryStore{}
	c := config.Config{Parallelism: 1, Providers: map[string]config.Provider{"p": {APIKey: "private-key", SOCKS5: "private-proxy"}}, Repositories: map[string]config.Repository{"r": {OutputDir: "generated"}}, Pipelines: map[string]config.Pipeline{"x": testPipeline("text", "custom", "original", ".txt")}}
	engine := &pipeline.Engine{Git: repo, Definitions: map[string]pipeline.Definition{"test-text": testDefinition{ids: []string{"custom"}}}, NewProvider: func(config.Provider) (pipeline.Provider, error) { runs++; return provider, nil }}
	service, err := New(c, t.TempDir(), Dependencies{Pipeline: engine, History: store})
	if err != nil {
		t.Fatal(err)
	}
	defer service.Close()
	// The service owns its configuration: callers cannot mutate a queued run.
	c.Pipelines["x"] = testPipeline("text", "custom", "changed", ".txt")
	if err = service.Enqueue("x", "r", "p"); err != nil {
		t.Fatal(err)
	}
	tasks, _ := service.Snapshot()
	id := tasks[0].ID
	failed := waitTask(t, service, id)
	if failed.Status != "failed" || failed.SHA != "saved-sha" || !provider.closed || runs != 1 || failed.Usage.Total != 7 {
		t.Fatalf("unexpected execution: %+v", failed)
	}
	if failed.Provider.APIKey != "" || failed.Provider.SOCKS5 != "" {
		t.Fatal("snapshot exposed credentials")
	}
	failed.Pipeline.Stages["custom.generate"]["instruction"] = "snapshot mutation"
	fresh, _ := service.Snapshot()
	if fresh[0].Pipeline.Stages["custom.generate"]["instruction"] != "original" {
		t.Fatal("snapshot changed internal task state")
	}
	if store.tasks[0].Provider.APIKey != "" || store.tasks[0].Provider.SOCKS5 != "" {
		t.Fatal("history exposed credentials")
	}
	repo.reject = false
	if err = service.RetryPublish(id); err != nil {
		t.Fatal(err)
	}
	done := waitTask(t, service, id)
	if done.Status != "succeeded" || runs != 1 || repo.commits != 1 || repo.pushes != 2 || repo.pulls != 1 {
		t.Fatalf("retry regenerated the task: %+v", done)
	}
}

func TestHistoryInitializationFailure(t *testing.T) {
	sentinel := errors.New("storage unavailable")
	_, err := New(config.Config{}, t.TempDir(), Dependencies{Pipeline: &pipeline.Engine{}, History: &memoryStore{err: sentinel}})
	if !errors.Is(err, sentinel) {
		t.Fatalf("storage failure was hidden: %v", err)
	}
}

func (*stubRepository) Head(context.Context, string) (string, error) { return "saved-sha", nil }
func (*stubRepository) Clean(context.Context, string) (bool, error)  { return true, nil }
