package task

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"slop-generator/internal/config"
	"slop-generator/internal/inference"
	"slop-generator/internal/pipeline"
)

type memoryStore struct {
	tasks []Task
	err   error
}

func (s *memoryStore) Load() ([]Task, error) { return slices.Clone(s.tasks), s.err }
func (s *memoryStore) Save(tasks []Task) error {
	if s.err != nil {
		return s.err
	}
	s.tasks = slices.Clone(tasks)
	return nil
}

type stubProvider struct{ closed bool }

func (*stubProvider) Generate(context.Context, inference.Request) (inference.Result, error) {
	return inference.Result{Content: "generated by stub", Usage: &inference.Usage{Total: 7}}, nil
}
func (p *stubProvider) Close() { p.closed = true }

type stubPipeline struct{ runs int }

func (p *stubPipeline) Run(ctx context.Context, r pipeline.Runtime) error {
	p.runs++
	response, err := r.Generator.Generate(ctx, inference.Request{})
	if err != nil {
		return err
	}
	r.RecordUsage(response.Usage)
	if err = os.WriteFile(filepath.Join(r.OutputDir, "custom.txt"), []byte(response.Content), 0600); err != nil {
		return err
	}
	r.JobComplete("custom")
	return nil
}

type stubRepository struct {
	commits, pushes, pulls int
	reject                 bool
	pullErr                error
}

func (*stubRepository) Identity(context.Context, config.Repository) (string, error) {
	return "stub-repository", nil
}
func (*stubRepository) Prepare(_ context.Context, _ config.Repository, work string) (string, error) {
	return "base", os.MkdirAll(work, 0700)
}
func (r *stubRepository) Commit(_ context.Context, work, output, message, hooks string) (string, error) {
	r.commits++
	if _, err := os.Stat(filepath.Join(output, "custom.txt")); err != nil {
		return "", err
	}
	return "saved-sha", nil
}
func (r *stubRepository) Publish(context.Context, string, string, string) error {
	r.pushes++
	if r.reject {
		return errors.New("temporary publication failure")
	}
	return nil
}

func (r *stubRepository) Pull(context.Context, config.Repository) error { r.pulls++; return r.pullErr }

func TestInjectedPipelineAndAdapters(t *testing.T) {
	provider := &stubProvider{}
	runner := &stubPipeline{}
	repo := &stubRepository{reject: true}
	store := &memoryStore{}
	c := config.Config{Parallelism: 1, Providers: map[string]config.Provider{"p": {APIKey: "private-key", SOCKS5: "private-proxy"}}, Repositories: map[string]config.Repository{"r": {OutputDir: "generated"}}, Pipelines: map[string]config.Pipeline{"x": {Type: "custom", Jobs: []config.Job{{ID: "original"}}}}}
	service, err := New(c, t.TempDir(), Dependencies{NewProvider: func(config.Provider) (Provider, error) { return provider, nil }, Pipeline: runner, Git: repo, History: store})
	if err != nil {
		t.Fatal(err)
	}
	defer service.Close()
	// The service owns its configuration: callers cannot mutate a queued run.
	c.Pipelines["x"] = config.Pipeline{Jobs: []config.Job{{ID: "changed"}}}
	if err = service.Enqueue("x", "r", "p"); err != nil {
		t.Fatal(err)
	}
	tasks, _ := service.Snapshot()
	id := tasks[0].ID
	failed := waitTask(t, service, id)
	if failed.Status != "failed" || failed.SHA != "saved-sha" || !provider.closed || runner.runs != 1 || failed.Usage.Total != 7 {
		t.Fatalf("unexpected execution: %+v", failed)
	}
	if failed.Provider.APIKey != "" || failed.Provider.SOCKS5 != "" {
		t.Fatal("snapshot exposed credentials")
	}
	failed.Pipeline.Jobs[0].ID = "snapshot mutation"
	fresh, _ := service.Snapshot()
	if fresh[0].Pipeline.Jobs[0].ID != "original" {
		t.Fatal("snapshot changed internal task state")
	}
	if store.tasks[0].Provider.APIKey != "" || store.tasks[0].Provider.SOCKS5 != "" {
		t.Fatal("history exposed credentials")
	}
	repo.reject = false
	if err = service.RetryPublish(id); err != nil {
		t.Fatal(err)
	}
	done := waitTask(t, service, id)
	if done.Status != "succeeded" || runner.runs != 1 || repo.commits != 1 || repo.pushes != 2 || repo.pulls != 1 {
		t.Fatalf("retry regenerated the task: %+v", done)
	}
}

func TestHistoryInitializationFailure(t *testing.T) {
	sentinel := errors.New("storage unavailable")
	_, err := New(config.Config{}, t.TempDir(), Dependencies{NewProvider: func(config.Provider) (Provider, error) { return &stubProvider{}, nil }, Pipeline: &stubPipeline{}, Git: &stubRepository{}, History: &memoryStore{err: sentinel}})
	if !errors.Is(err, sentinel) {
		t.Fatalf("storage failure was hidden: %v", err)
	}
}
